AWSTemplateFormatVersion: '2010-09-09'
Resources:
  HelloWorldGreetingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GreetingTableName
      AttributeDefinitions:
        - AttributeName: greetingId
          AttributeType: S
      KeySchema:
        - AttributeName: greetingId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref Rcu
        WriteCapacityUnits: !Ref Wcu
  AttendanceWhiteChannelTableName:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref WhiteChannelTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: channelId
          AttributeType: S
      KeySchema:
        - AttributeName: channelId
          KeyType: HASH
