AWSTemplateFormatVersion: '2010-09-09'
Resources:

  AttendanceWhiteChannelTableName:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref WhiteChannelTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: channelId
          AttributeType: S
      KeySchema:
        - AttributeName: channelId
          KeyType: HASH
